spring.application.name=tp3MiceliTabuada

spring.datasource.url=jdbc:mysql://localhost:3306/db_tp3_miceli_tabuada?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# Para tu compu (cambiá 1234 por la contraseña que pusiste al instalar MySQL)
spring.datasource.username=root
spring.datasource.password=1234
#para la compu del cole
#spring.datasource.password=jxPE3wgLnHu0LpJcwuQmoA==
#spring.datasource.username=alumno26.miceli.francisco


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
# La clave debe tener al menos 32 caracteres para HS256
jwt.secret=clave-super-secreta-tp3-miceli-tabuada-2026
# 1 hora en milisegundos
jwt.expiration=3600000
