spring.application.name=backEnd

# -----------------------------------------------
# MySQL
# -----------------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/futbol5ya_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=alumnoipm
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# -----------------------------------------------
# H2 - Base de datos en memoria (comentado)
# -----------------------------------------------
# spring.datasource.url=jdbc:h2:mem:futbol5ya_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# Hibernate - actualiza las tablas sin borrar datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081