spring.application.name=backEnd

# Configuracion de base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/futbol5ya_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=alumno26.miceli.francisco@ipm.edu.ar
spring.datasource.password=micelitabuad

# Hibernate - genera/actualiza las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8081